Django7/oct05/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/", views.detail, name="detail"),
]

Django7/oct05/oct05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ppap.urls")),
    path("accounts/", include("accounts.urls")),
]

Django7/oct05/ppap/urls.py
from django.urls import path
from . import views

app_name = "ppap"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
]

Django7/oct05/ppap/models.py
from django.db import models

# Create your models here.
"""
게시판 기능 
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/시간)
"""


class Ppap(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django7/oct05/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

# from .models import User
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)

Django7/oct05/ppap/forms.py
from .models import Ppap
from django import forms


class PpapForm(forms.ModelForm):
    class Meta:
        model = Ppap
        fields = ["title", "content"]

Django7/oct05/accounts/views.py
from multiprocessing import context
from django.shortcuts import render, redirect

# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("ppap:index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {"user": user}
    return render(request, "accounts/detail.html", context)

Django7/oct05/ppap/views.py
from django.shortcuts import render, redirect

from .forms import PpapForm
from .models import Ppap

# Create your views here.
def index(request):
    ppaps = Ppap.objects.order_by("-id")
    context = {"ppaps": ppaps}
    return render(request, "ppap/index.html", context)


def create(request):
    # get으로 받는 코드
    # if request.method == "GET":
    #     ppap = request.GET
    #     context = {"ppap": ppap}

    #     return render(request, "ppap/create.html", context)
    # else:
    #     title = request.POST.get("title")
    #     content = request.POST.get("content")
    #     Ppap.objects.create(title=title, content=content)

    #     return redirect("/")
    if request.method == "POST":
        # DB에 저장하는 로직
        ppap_form = PpapForm(request.POST)
        if ppap_form.is_valid():
            ppap_form.save()
            return redirect("ppap:index")
    else:
        ppap_form = PpapForm()
    context = {"ppap_form": ppap_form}
    return render(request, "ppap/create.html", context=context)


def detail(request, pk):
    ppap = Ppap.objects.get(pk=pk)
    context = {"ppap": ppap}
    return render(request, "ppap/detail.html", context)


def delete(request, pk):
    Ppap.objects.get(pk=pk).delete()
    return redirect("/")


def update(request, pk):
    # 폼하기전
    # return render(request, "ppap/update.html", context)
    # ppap = Ppap.objects.get(pk=pk)
    # if request.method == "POST":
    #     ppap.title = request.POST.get("title")
    #     ppap.content = request.POST.get("content")
    #     ppap.save()
    #     return redirect("/")
    # else:
    #     context = {"ppap": ppap}
    # return render(request, "ppap/update.html", context)

    # 폼하고나서
    ppap = Ppap.objects.get(pk=pk)

    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        ppap_form = PpapForm(request.POST, instance=ppap)
        if ppap_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            ppap_form.save()
            return redirect("ppap:detail", ppap.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 ppap_form을 랜더링
    else:
        # GET : Form을 제공
        ppap_form = PpapForm(instance=ppap)
    context = {"ppap_form": ppap_form, "ppap": ppap}
    return render(request, "ppap/update.html", context)

Django7/oct05/accounts/templates/accounts/detail.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <h1>{{ user.username }}님의 프로필</h1>
  </body>

</html>

Django7/oct05/accounts/templates/accounts/signup.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Document</title>
  </head>

  <body>
    <h1>회원가입</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% comment %} {{form.as_p}} {% endcomment %}
      {% bootstrap_form form %}
      {%bootstrap_button button_type="submit" content="OK" %}
    </form>
  </body>

</html>

Django7/oct05/ppap/templates/ppap/create.html
{%extends 'base.html'%}
{%block content%}
  {% load django_bootstrap5 %}
  {%bootstrap_css %}
  {% bootstrap_javascript %}
  <h1 class="text-center p-5">작성하기</h1>
  <form action="{% url 'ppap:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form ppap_form %}
    <!-- <label for="title">제목 : {{ppap.title}}</label> <input type="text" name="title" id="title" /> <label for="content">내용 : {{ppap.content}}</label> <textarea name="content" id="content" cols="30" rows="10"></textarea> -->
    <input class="btn btn-outline-dark" type="submit" value="글쓰기"/>
  </form>

{%endblock %}

Django7/oct05/ppap/templates/ppap/detail.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center p-5">게시판</h1>
  <div class="m-5 p-3 border border-3 border-dark rounded">
    <h3>제목 :
      {{ppap.title}}</h3>
    <h5>내용 :
      {{ppap.content}}</h5>
    <p>만든날짜 :
      {{ppap.created_at}}
      | 수정날짜 :
      {{ppap.updated_at}}</p>
    <a class="btn btn-outline-dark" href="{%url 'ppap:delete' ppap.pk%}">
      삭제
    </a>
    <a class="btn btn-outline-dark" href="{%url 'ppap:update' ppap.pk%}">
      수정
    </a>
  </div>

{% endblock %}

Django7/oct05/ppap/templates/ppap/index.html
{% extends 'base.html' %}
{% block content %}{%load static%}
  <h1 class="text-center p-5">게시판</h1>
  <img class="container-fluid" src="{% static 'hedgehog_animal_cute_small_porcupine_autumn_icon_150807.png'%}" alt=""/>
  <div class="text-center m-3">
    <a href="{% url 'ppap:create' %}" type="button" class="btn btn-outline-dark">
      글 쓰기
    </a>
  </div>
  <hr/>

  {% for ppap in ppaps %}
    <div class="m-5 p-3 border border-3 border-dark rounded">
      <a class="text-decoration-none" href="{%url 'ppap:detail' ppap.pk%}">
        <h3>제목 :
          {{ppap.title}}</h3>
      </a>
      <h5>내용 :
        {{ppap.content}}</h5>
      <p>만든날짜 :
        {{ppap.created_at}}
        | 수정날짜 :
        {{ppap.updated_at}}</p>
    </div>
    {% endfor%}
  {% endblock %}

Django7/oct05/ppap/templates/ppap/update.html
{%extends 'base.html'%}
{%block content%}
  <form action="{% url 'ppap:update' ppap.pk%}" method="POST">
    {% csrf_token %}
    <label for="title">제목 :
      {{ppap.title}}</label>
    <input type="text" name="title" id="title"/>
    <label for="content">내용 :
      {{ppap.content}}</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value="글쓰기"/>
  </form>

{%endblock %}