Django15/accounts/urls.py
from django.urls import path
from . import views

# app_name은 왜 쓸까요?
# 우리는 기본적으로 URL을 모두 변수화해서 쓰고 있음
# Template, View에서 직접 '/accounts/' X
# app_name과 path 이름으로

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
    path("<int:hot_pk>/marker/", views.marker, name="marker"),
]

Django15/articles/urls.py
# URL설정을 app 단위로!

from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/like/", views.like, name="like"),
    path("admin_create/", views.admin_create, name="admin_create"),
    path("<int:hot_pk>/hotplace", views.hotplace, name="hotplace"),
]

Django15/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django15/articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from pjt.settings import AUTH_USER_MODEL

# Create your models here.
"""
게시판 기능 
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/시간)
"""
# 1. 모델 설계 (DB 스키마 설계)
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Admin(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(
        default="images/default_image.jpeg",
        upload_to="images/",
        blank=True,
    )
    address = models.CharField(max_length=100)
    contact = models.CharField(max_length=14)
    camp_type = models.CharField(max_length=20)
    season = models.CharField(max_length=20)
    active_day = models.CharField(max_length=10)
    homepage = models.CharField(max_length=40, blank=True)
    reservation = models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    geography = models.CharField(max_length=20)


class Photo(models.Model):
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE)
    auser = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(
        default="photos/default_image.jpeg",
        upload_to="photos/",
        blank=True,
    )

Django15/articles/forms.py
from django import forms
from .models import Article, Comment, Admin, Photo


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]


class AdminForm(forms.ModelForm):
    class Meta:
        model = Admin
        fields = (
            "name",
            "image",
            "address",
            "contact",
            "camp_type",
            "season",
            "active_day",
            "reservation",
            "geography",
        )


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ("image",)

Django15/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Article, Admin
from .forms import ArticleForm, CommentForm, AdminForm
from django.http import JsonResponse

# Create your views here.

# 요청 정보를 받아서..
def index(request):
    # 게시글을 가져와서..
    articles = Article.objects.order_by("-pk")
    all_article = Admin.objects.all()
    # Template에 전달한다.
    context = {
        "articles": articles,
        "all_article": all_article,
    }
    return render(request, "articles/index.html", context)


# def new(request):
#     article_form = ArticleForm()
#     context = {
#         'article_form': article_form
#     }
#     return render(request, 'articles/new.html', context=context)


@login_required
def create(request):
    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            # 로그인한 유저 => 작성자네!
            article.user = request.user
            article.save()
            messages.success(request, "글 작성이 완료되었습니다.")
            return redirect("articles:index")
    else:
        article_form = ArticleForm()
    context = {"article_form": article_form}
    return render(request, "articles/form.html", context=context)


def detail(request, pk):
    # 특정 글을 가져온다.
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    # template에 객체 전달
    context = {
        "article": article,
        "comments": article.comment_set.all(),
        "comment_form": comment_form,
    }
    return render(request, "articles/detail.html", context)


@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == "POST":
            # POST : input 값 가져와서, 검증하고, DB에 저장
            article_form = ArticleForm(request.POST, request.FILES, instance=article)
            if article_form.is_valid():
                # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
                article_form.save()
                messages.success(request, "글이 수정되었습니다.")
                return redirect("articles:detail", article.pk)
            # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
        else:
            # GET : Form을 제공
            article_form = ArticleForm(instance=article)
        context = {"article_form": article_form}
        return render(request, "articles/form.html", context)
    else:
        # 작성자가 아닐 때
        # (1) 403 에러메시지를 던져버린다.
        # from django.http import HttpResponseForbidden
        # return HttpResponseForbidden()
        # (2) flash message 활용!
        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("articles:detail", article.pk)


@login_required
def comment_create(request, pk):
    print(request.POST)
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        context = {"content": comment.content, "userName": comment.user.username}
        return JsonResponse(context)


@login_required
def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # 만약에 로그인한 유저가 이 글을 좋아요를 눌렀다면,
    # if article.like_users.filter(id=request.user.id).exists():
    if request.user in article.like_users.all():
        # 좋아요 삭제하고
        article.like_users.remove(request.user)
        is_liked = False
    else:
        # 좋아요 추가하고
        article.like_users.add(request.user)
        is_liked = True
    # 상세 페이지로 redirect
    context = {"isLiked": is_liked, "likeCount": article.like_users.count()}
    return JsonResponse(context)


def admin_create(request):
    if request.method == "POST":
        form = AdminForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("articles:index")
    else:
        form = AdminForm()
    context = {
        "form": form,
    }
    return render(request, "articles/admin_create.html", context)


def hotplace(request, hot_pk):
    # 특정 글을 가져온다.
    admin = Admin.objects.get(pk=hot_pk)
    comment_form = CommentForm()
    # template에 객체 전달
    context = {
        "admin": admin,
        "comment_form": comment_form,
    }
    return render(request, "articles/hotplace.html", context)

Django15/articles/templates/articles/admin_create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block body %}



<div style="text-align: center; background-color: rgba(203, 210, 216, 0.733); max-width:700px; padding:60px; margin:4rem auto">
	<div>
		<h1>관리자전용 캠프 생성페이지 </h1>
	</div>
	<div>
		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{% bootstrap_form form %}
			<br>
			<input type="submit" class="btn btn-dark rounded-pill mt-3">
		</form>
	</div>
</div>

{% endblock body %}

Django15/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %} 
<h1>{{ article.title }}</h1>
<p>{{ article.pk }}번 게시글 | <a href="{% url 'accounts:detail' article.user.pk %}">{{ article.user.username }}</a></p>
<p>{{ article.created_at|date:"SHORT_DATETIME_FORMAT" }} | {{ article.updated_at|date:"y-m-d D" }}</p>
<p>FOLLOWING   {{ user.followings.count }} | FOLLOWER  {{ user.followers.count }}</p>
<div class="m-2">
  {% if request.user != article.user %}
    <div>
      <form action="{% url 'accounts:follow' article.user.pk%}" method='POST'>
        {% csrf_token %}
        {% if request.user in user.followers.all %}
          <input type="submit" class="btn btn-outline-secondary" value='Unfollow'>
        {% else %}
          <input type="submit" class="btn btn-outline-secondary" value='Follow'>
        {% endif %}
      </form>
    </div>
  {% endif %}
</div>


{% if request.user == article.user %}
<p>
  <a href="{% url 'articles:update' article.pk %}" class="text-decoration-none bnt bnt-outline-dark">수정하기</a>
</p>
{% endif %}
<hr>
<p>{{ article.content }} </p>
{% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}" width="400" height="300">
  <form action="{% url 'articles:like' article.pk %}" method='POST'>
    {% csrf_token %}
    {% if request.user in article.like_users.all %}
    <button class="btn btn-link text-danger">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-suit-heart-fill" viewbox="0 0 16 16">
        <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
      </svg>
    </button>
    {% else %}
    <button class="btn btn-link text-danger">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-suit-heart" viewbox="0 0 16 16">
        <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
      </svg>
    </button>
  </form>
  {% endif %}
  {% endif %}
<hr>
<h4 class="my-3">댓글</h4>
{% if request.user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form layout='floating'%}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endif %}
<hr>
{% for comment in comments %}
  <p> {{ comment.user.username }} | {{ comment.content }}</p>
  <hr>    
{% empty %}
  <p>댓글이 없어요 ㅠ_ㅠ</p>
{% endfor %}


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  //1.좋아요버튼
  const likeBtn = document.querySelector('#like-btn')
  //2.좋아요 버튼을 클릭하면 함수실행
  likeBtn.addEventListener('click', function (event) {
    // 서버로 비동기 요청을 하고 싶음
    console.log(event.target.dataset)
    axios({
      method: 'get',
      url: '/articles/${event.target.dataset.articleId}/like/'
    })
  .then(respones =>{
    console.log(respones)
  })
  })
</script>
<script>
  // 댓글!
  // (1) 댓글 폼
  const commentForm = document.querySelector('#comment-form')
  // (2) 제출하면, 함수 실행시킬래 
  // csrf 
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  commentForm.addEventListener('submit', function(event) {
    event.preventDefault();
    axios({
      method: 'post',
      url: `/articles/${event.target.dataset.articleId}/comments/`,
      headers: {'X-CSRFToken': csrftoken},
      data: new FormData(commentForm) // 폼에 있는 정보를 data로 넘겨줄 수 있도록 변환
    })
    .then(response => {
      console.log(response.data)
      // 댓글을 추가하는 로직
      const comments = document.querySelector('#comments')
      const p = document.createElement('p')
      p.innerText = `${response.data.userName} | ${response.data.content}`
      const hr = document.createElement('hr')
      comments.append(p, hr) 
      commentForm.reset()
    })
  })
</script>
{% endblock %}

Django15/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  {% if request.resolver_match.url_name == 'create' %}
    <h1>
      글쓰기
    </h1>
  {% else %}
    <h1>
      수정하기
    </h1>
  {% endif %}

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form article_form %}
    <input class="bnt my-3" style='color:#937DC2' type="submit" value="OK">
  </form>
{% endblock %}

Django15/articles/templates/articles/hotplace.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %} 
<div class="container">
  <div class="container mt-5">
    <div class="text-center">
      <h1 class="menu-title mb-5">{{ admin.name }}</h1>
    </div>
    <div class="row gx-3">
      <div class="col-7 d-flex justify-content-center">
        <div class="detail-img-div">
          <img class="detail-img" src="{{ admin.image.url }}">
        </div>
      </div>
      <div class="col-5 mb-5">
        <table class="table">
          <tbody>
            <!-- 주소 -->
            <tr>
              <th class="col-3">주소</th>
              <td class="col-9">{{ admin.address }}</td>
            </tr>
            <!-- 업체 연락처 -->
            <tr>
              <th class="col-3">문의처</th>
              <td class="col-9">{{ admin.contact }}</td>
            </tr>
            <!-- 캠핑장 유형 -->
            <tr>
              <th class="col-3">캠핑장 유형</th>
              <td class="col-9">{{ admin.camp_type }}</td>
            </tr>
            <!-- 바닥 유형 -->
            <tr>
              <th class="col-3">바닥 유형</th>
              <td class="col-9">{{ admin.geography }}</td>
            </tr>
            <!-- 이용 시간 -->
            <tr>
              <th class="col-3">이용 시간</th>
              <td class="col-9">{{ admin.season }}</td>
            </tr>
            <!-- 이용요금 -->
            <tr>
              <th class="col-3">이용 요금</th>
              <td class="col-9">{{ admin.active_day }}</td>
            </tr>
            <!-- 홈페이지 -->
            <tr>
              <th class="col-3">홈페이지</th>
              <td class="col-9"><a href="{{ admin.homepage }}">홈페이지 바로가기</a></td>
            </tr>
            <!-- 예약 방법 -->
            <tr>
              <th class="col-3">예약 방법</th>
              <td class="col-9">{{ admin.reservation }}</td>
            </tr>
          </tbody>
        </table>
        <a href="{% url 'accounts:marker' article.pk %}" class="btn btn-dark rounded-pill col-3 mt-3">
          {% if article not in request.user.marker.all %}
          <i class="bi bi-bookmark-star"></i>
          즐겨찾기
          {%else%}
          <i class="bi bi-bookmark-star-fill"></i>
          즐겨찾기 해제
          {%endif%}
        </a>
        {% comment %} <a class="btn btn-dark rounded-pill col-4 mt-3 mx-3" href="{% url 'reviews:create' article.pk %}"> 리뷰 작성하기</a> {% endcomment %}
        {% if user.is_superuser %}
        <a class="btn btn-dark rounded-pill col-3 mt-3 mx-5" href="{url 'articles:delete' article.pk}">삭제하기</a>
        {% endif %}
{% endblock %}

Django15/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
{% endblock %}

{% block body %}
  <h1>LOOK at THAT!</h1>
  {% if request.user.is_authenticated %}
    <a class="btn btn-outline my-3 float-right" href="{% url 'articles:create' %}" style='color:#8758FF'>NEW CREATE</a>
  {% endif %}

  <div class="row">
    {% for article in articles %}
      <div class="col-4 my-3">
        <div class="card">
          {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="text-muted">
              <a class='text-decoration-none' href="{% url 'accounts:detail' article.user.pk %}">{{ article.user.username }}</a>
            </p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-outline my-3" style='color:#7978FF'>Click Me!</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="container mb-5 text-center">
    <h2 class="menu-title">인기순(테마별)</h2>
    <div class="row">
  
      {% for admin in all_article %}
  
      <div class="col-12 col-sm-6 col-lg-4 my-3">
        <a href="{% url 'articles:hotplace' admin.pk %}" class="btn btn-light">
          <div class="card">
            {% if admin.image %}
            <img src="{{ admin.image.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
          {% endif %}
            <div class="card-body">
              <h5 class="card-title fw-bold">{{admin.name}} </h5>
              <p class="card-text">{{admin.camp_type}}</p>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

Django15/articles/templates/articles/photo-form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<div class="container">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form photo_form %}
    {% bootstrap_button button_type="submit" button_class="btn btn-primary" content="제출" %}
  </form>
</div>

{% endblock body %}