Django10/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
]

Django10/oct13/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
]

Django10/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

Django10/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )

Django10/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
def home(request):
    users = User.objects.all()
    context = {"users": users}
    return render(request, "accounts/home.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:home")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {"user": user}
    return render(request, "accounts/detail.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:home")
    else:
        form = AuthenticationForm()

    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:home")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)

    else:
        form = CustomUserChangeForm(instance=request.user)

    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)

Django10/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block content %}

  <div class="container mt-5 border border-3 border-dark rounded">
    <h1 class="p-3">{{ user.username }}님의 프로필</h1>
    <div class="container">
      <p>{{ user.id }}번</p>
      <p>이메일 :
        {{ user.email }}</p>
      <p>
        가입일 :
        {{ user.date_joined }}
      </p>
      <a href="{% url "accounts:home" %}" class='btn btn-dark text-white mb-3'>홈으로</a>
      <a href="{% url 'accounts:update' %}" class='btn btn-dark text-white mb-3'>회원정보 수정</a>
    </div>
  </div>

{% endblock %}

Django10/accounts/templates/accounts/home.html
{% extends 'base.html' %}{% load django_bootstrap5 %}
{% block content %}
  <h1 class="text-center">HOME</h1>

  <div class='container'>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>#</th>
          <th scope='col'>username</th>
          <th scope='col'>email</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <th scope='row'>{{ user.id }}</th>
            <td>
              <a href='{% url 'accounts:detail' user.pk %}'>{{ user.username }}</a>
            </td>
            <td>{{ user.email }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="container">
    <a href="{% url 'accounts:login' %}" class="btn btn-dark text-white">로그인</a>
    <a href="{% url 'accounts:signup' %}" class="btn btn-dark text-white">회원가입</a>
  </div>
{% endblock %}

Django10/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

  <h1 class="text-center">
    로그인
  </h1>
  <div class='container'>
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id">사용자 아이디</label>
        <input type="text" class="form-control" name="username" id="username">
      </div>
      <div class="mb-3">
        <label for="password">비밀번호</label>
        <input type="password" class="form-control" name="password" id="password">
      </div>
      <div class="mb-3">
        <button type="submit" class="btn btn-outline-secondary">로그인</button>
        <a type="button" class="btn btn-secondary" href="{% url 'accounts:signup' %}">회원가입</a>
      </div>
    </div>
  </form>

{% endblock %}

Django10/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class='text-center'>Update Profile</h1>
  <div class='container'>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type='submit' class='btn btn-dark text-white mb-3'></input>
    </form>
  </div>
{% endblock %}